name: Indent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: heltai/dealii:vscode

    steps:
    - uses: actions/checkout@v2
    - name: Check indentation
      run: |
         git config --global --add safe.directory /__w/fem-with-dealii-2022/fem-with-dealii-2022
         ./scripts/check_indentation.sh 
